-keep class io.github.rajnishkmehta.dhwanicontrol.** extends android.app.Activity { *; }
-keep class io.github.rajnishkmehta.dhwanicontrol.** extends android.app.Service { *; }
-keep class io.github.rajnishkmehta.dhwanicontrol.** extends android.content.BroadcastReceiver { *; }
